repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10
        args: ["--line-length=100", "--target-version=py310"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package.lock.json|go.sum|pnpm-lock.yaml|yarn.lock|poetry.lock

  - repo: https://github.com/rubik/radon
    rev: 6.0.1
    hooks:
      - id: radon
        args: ["cc", "-nc", "-s", "-i"]